# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rspec", "~> 3.11"

gem 'colorize', '~> 0.8.1'

gem 'tty-font', '~> 0.5.0'

gem 'pastel', '~> 0.8.0'

gem 'tty-spinner', '~> 0.9.3'

gem 'ruby2d', '~>0.9.2'